name: animated_shapes
description: Animated geometric shapes in Flutter - Give any offset and the shape will animate to that position from current position
version: 0.0.3
homepage: https://github.com/TechieBlossom/animated_shapes
repository: https://github.com/TechieBlossom/animated_shapes
issue_tracker: https://github.com/TechieBlossom/animated_shapes/issues

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

screenshots:
  - description: "Animation"
    path: screenshots/animation.webm
  - description: "Scalene Triangle"
    path: screenshots/scalene_triangle.png
  - description: "Kite"
    path: screenshots/kite.png
  - description: "Octagon"
    path: screenshots/octagon.png

topics:
  - animation
  - shapes

funding:
  - https://github.com/sponsors/techieblossom
